config/routes.rb
Rails.application.routes.draw do
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :widgets
  resource  :my_widgets, only: :show

  root 'widgets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < Struct.new(:first_name,
                        :last_name,
                        :email,
                        :password,
                        :image_url)

  include ActiveModel::Model
end

app/models/widget.rb
class Widget < Struct.new(:id,
                          :name,
                          :description,
                          :kind,
                          :owner)

  include ActiveModel::Model

  def self.from_hash(hash)
    obj = self.new
    hash.each {|key,value| obj.send("#{key}=", value)}
    obj
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_widgets_controller.rb
class MyWidgetsController < ApplicationController
  def show
    args = { path: 'me/widgets?', token: session[:access_token] }
    response = UsersRestService.new(args).get
    @widgets = WidgetsParserService.parse(response)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    session_params = safe_params.to_h.merge({'grant_type': 'password'})
    
    begin
      response = SessionsRestService.new(path: 'token', params: session_params).post
      log_in JSON.parse(response.body)
      redirect_to my_widgets_path
    rescue
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

    def safe_params
      params.require(:session).permit(:username, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :authenticate_user!, except: [:new, :create]

  def show
    args = { path: params[:id], token: session[:access_token] }
    response = UsersRestService.new(args).get
    @user = UserParserService.parse(response)

    args = { path: params[:id] + '/widgets?term=visible', token: session[:access_token] }
    response = UsersRestService.new(args).get
    @widgets = WidgetsParserService.parse(response)
  end

  def new
    @user = User.new
  end

  def create
    begin
      response = UsersRestService.new(params: safe_params.to_h).post
      log_in JSON.parse(response.body)
      redirect_to my_widgets_path
    rescue
      flash[:danger] = 'Error message'
      render 'new'
    end
  end

  private

    def safe_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :image_url)
    end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  def index
    args = { path: 'visible?term=a' }
    response = WidgetsRestService.new(args).get
    @widgets = WidgetsParserService.parse(response)
  end

  def new
    @widget = Widget.new
  end

  def create
    args = { params: safe_params.to_h, token: session[:access_token] }
    begin
      response = WidgetsRestService.new(args).post
      redirect_to my_widgets_path, notice: 'Widget created!'
    rescue
      flash[:danger] = 'Error message'
      render 'new'
    end
  end

  def edit
    args = { path: "#{params[:id]}/?", token: session[:access_token] }
    response = WidgetsRestService.new(args).get
    @widget = WidgetParserService.parse(response)
  end
  
  def update
    #TODO
  end

  def destroy
    #TODO
  end

  private

    def safe_params
      params.require(:widget).permit(:name, :description, :kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:access_token].present?
  end

  def log_in(user_json)
    data = user_json['data']
    session[:access_token]  = data['token']['access_token']
    session[:refresh_token] = data['token']['refresh_token']
  end

  def log_out
    session.delete :access_token
    session.delete :refresh_token
  end

  def authenticate_user!
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/views/layouts/_flash.html.erb
<div class="container my-2">
  <% flash.each do |type, msg| %>
    <div class="alert alert-warning alert-dismissable fade show">
      <%= msg %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showoff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <%= link_to "ShowOff", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
           <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "My widgets", my_widgets_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Profile", "#", class: "dropdown-item" %>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= render partial: 'layouts/flash', flash: flash %> 
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/my_widgets/show.html.erb
<h3>My Widgets</h3>
<%= link_to 'New Widget', new_widget_path %>

<% if @widgets.present? %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th colspan="2">
      </tr>
    </thead>
    <tbody>
      <% @widgets.each do |widget| %>
        <tr>
          <td><%= widget.id %></th>
          <td><%= widget.name %></td>
          <td><%= widget.description %></td>
          <td><%= link_to 'Edit', edit_widget_path(widget.id) %></td>
          <td><%= link_to 'Delete', widget_path(widget.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class='mt-3'>No widgets for this user</p>
<% end %>

app/views/users/new.html.erb
<h3>Sign up</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', required: true %>
      </div>

      <div class="form-group">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, class: 'form-control', required: true %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :kind %>
    <%= f.select :kind, options_for_select(["visible","hidden"]), {}, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/widgets/_index.html.erb
<% if widgets.present? %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">User</th>
      </tr>
    </thead>
    <tbody>
      <% widgets.each do |widget| %>
        <tr>
          <td><%= widget.id %></th>
          <td><%= widget.name %></td>
          <td><%= widget.description %></td>
          <td><%= link_to widget.user['name'], user_path(widget.user['id']) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class='mt-3'>No widgets for this user</p>
<% end %>

app/views/widgets/edit.html.erb
<h3>Edit Widget</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/widgets/index.html.erb
<h3>All Widgets</h3>

<%= render partial: "index", locals: {widgets: @widgets} %>

app/views/widgets/new.html.erb
<h3>New Widget</h3>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>